import os
import signal
import subprocess
import json
import time
from pathlib import Path
from datetime import datetime
from typing import Callable, Sequence, Tuple, ClassVar, Protocol, Optional, Type
from dataclasses import dataclass
import logging
import shlex

# Standalone open source

"""
Some terms:
  PulseAudio: Utility server to route and mix audio on linux.
  Pavucontrol: GUI application to view PulseAudio mix and config one tab at a time.
  Audio Device: Hardware device capable of integrating with PulseAudio 
  Input Audio Device: Any device plugged into PulseAudio to input audio. Can be any of: Hardware, Virtual or Monitor.
  Hardware Input Audio Device: Physical hardware peripheral device plugged into computer capable of sending audio signals into PulseAudio.
  Virtual Input Audio Device: 
  Monitor Input Audio Device: Audio from Audio Output Device capable of being plugged into PulseAudio as input. 
  Output Audio Device: Any device plugged into PulseAudio to output audio. Can be any of: Hardware, Virtual.
  Hardware Output Audio Device: Physical hardware peripheral device plugged into computer capable of emitting audio from PulseAudio.
  Virtual Output Audio Device:
  Stream: 
  Loopback:
  Playback Stream: Streams of audio coming from either: Application Stream or Virtual Stream.
  Application Playback Stream: Audio coming from running application like web browser, DAW, media player.
  Virtual Playback Stream: 
  Loopback Playback Stream: Virtual Playback Stream coming from Monitor Input Audio Device of some Output Audio Device played back through.
  Recording Stream: Streams of audio being written can be either: Application Stream or Virtual Stream. 
  Application Recording Stream: Stream of audio being captured for recording by recording application.
  Virtual Recording Stream: 
  Loopback Recording Stream: 


From AI:
===============================================================================
PULSEAUDIO / PIPEWIRE TERMINOLOGY REFERENCE
===============================================================================

Core Concepts & Tools:
----------------------
PulseAudio / PipeWire : Background sound server on Linux responsible for routing,
                        mixing, buffering, and processing audio streams across
                        hardware and software applications.
Pavucontrol           : GTK GUI utility ("PulseAudio Volume Control") used to view
                        and interactively re-route active audio streams and devices.
pactl                 : Command line utility ("PulseAudio Control") used to interact
                        with PulseAudio by command line interface (CLI).

Nodes & Devices:
----------------
Sink (Output Device)   : Any target endpoint where audio is SENT to be played or mixed.
                     • Hardware Sink: Physical output device (e.g., Headphones, USB DAC, Speakers).
                     • Virtual Sink: Software-defined dummy output created via 'module-null-sink'
                       (e.g., 'call_mix') used to collect and mix multiple playback sources.

Source (Input Device)  : Any origin endpoint where audio is READ from.
                      • Hardware Source: Physical input peripheral (e.g., Headset Mic, USB Mic).
                      • Virtual Source: Software input stream or remapped virtual channel.
                      • Monitor Source: Automatically generated virtual input attached to EVERY Sink
                        (e.g., 'call_mix.monitor', 'alsa_output...monitor'). Allows capturing whatever
                        audio is currently playing through that Sink.

Streams & Connections:
----------------------
Playback (Sink-Input) : An active PLAYBACK stream feeding audio INTO a Sink.
                     • Application Playback: Audio generated by a running app (e.g., Chrome, Spotify, Firefox).
                     • Loopback Playback: Audio fed into a Sink from another Source via 'module-loopback'.

Recording (Source-Output)  : An active RECORDING stream pulling audio OUT of a Source.
                    • Application Recording: Audio being captured by an app (e.g., FFmpeg, OBS, Teams mic input).
                    • Loopback Recording: Audio tapped from a Source to be routed into a Sink via 'module-loopback'.

Routing Mechanics:
------------------
Module                : A dynamic plugin loaded into PulseAudio (e.g., 'module-null-sink', 'module-loopback').
                        Unloaded upon server restart or via 'pactl unload-module <id>'.
Loopback              : A virtual bridge ('module-loopback') connecting one Source directly to one Sink,
                        allowing continuous real-time passthrough between devices.

-------------------------------------------------------------------------------
COMMON PITFALL / FEEDBACK LOOP WARNING:
Connecting a Sink's Monitor Source back into the SAME Sink via a Loopback module
creates a closed loop resulting in infinite echo / reverb corruption.
-------------------------------------------------------------------------------
"""


# -----------------------------------------------------------------------------
# Logger Protocol & Implementation
# -----------------------------------------------------------------------------

class LoggerProtocol(Protocol):
  """Interface for logging operations."""
  def debug(self, msg: str) -> "Self": ...
  def info(self, msg: str) -> "Self": ...
  def warning(self, msg: str) -> "Self": ...
  def error(self, msg: str) -> "Self": ...
# class LoggerProtocol

class FileLogger:
  "Default logger implementation routing output to a dedicated log file."
  def __init__(self, logFile: str = "audio_pipeline.log", level: int = logging.DEBUG):
    self.logFile = logFile; self.level = level
    self.logger = logging.getLogger("AudioPipeline"); self.logger.setLevel(level); self.setup()
  # logging interface
  def debug(self, msg: str) -> "Self": self.logger.debug(msg); return self
  def info(self, msg: str) -> "Self": self.logger.info(msg); return self
  def warning(self, msg: str) -> "Self": self.logger.warning(msg); return self
  def error(self, msg: str) -> "Self": self.logger.error(msg); return self
  # helpers
  def setup(self):
    self.avoidDuplicateConsolePrintsIfRootLoggerActive(); self.cleanUpFileHandlers(); self.createFileHandlers()
    self.addConsoleHandler(); return self
  def avoidDuplicateConsolePrintsIfRootLoggerActive(self): self.logger.propagate = False; return self
  def cleanUpFileHandlers(self):
    for handler in list(self.logger.handlers):
      if isinstance(handler, logging.FileHandler): handler.close(); self.logger.removeHandler(handler)
    return self
  def createFileHandlers(self):
    file_handler = logging.FileHandler(self.logFile, mode="a")
    file_handler.setLevel(self.level)  # Handlers MUST match the lower level!
    formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s", datefmt="%Y-%m-%d %H:%M:%S")
    file_handler.setFormatter(formatter); self.logger.addHandler(file_handler); return self
  def addConsoleHandler(self): 
    if not any(isinstance(h, logging.StreamHandler) for h in self.logger.handlers):
      console_handler = logging.StreamHandler(); console_handler.setLevel(self.level)
      console_handler.setFormatter(formatter); self.logger.addHandler(console_handler)
    return self
  def simpleSetup(self):
    if not self.logger.handlers:
      file_handler = logging.FileHandler(logFile)
      formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
      file_handler.setFormatter(formatter); self.logger.addHandler(file_handler)
    return self
# class FileLogger 

class NullLogger:
  """No-op logger implementation for tests or silent runs."""
  def __init__(self, *args, **kwargs): pass
  def debug(self, msg: str) -> "Self": pass
  def info(self, msg: str) -> "Self": pass
  def warning(self, msg: str) -> "Self": pass
  def error(self, msg: str) -> "Self": pass
# class NullLogger

# -----------------------------------------------------------------------------
# Shell Protocol, Exceptions, & Implementation
# -----------------------------------------------------------------------------

class ShellExecutionError(Exception):
  """Custom exception raised when a shell command fails."""
  def __init__(self, command: str, return_code: int, stdout: str, stderr: str):
    self.command = command
    self.return_code = return_code
    self.stdout = stdout
    self.stderr = stderr
    super().__init__(f"Command failed with return code {return_code}: '{command}'\n"
                     f"STDOUT: {stdout}\nSTDERR: {stderr}")
# class ShellExecutionError

class ShellProtocol(Protocol):
  """Interface for running and spawning shell commands."""
  def run(self, command: Sequence[str] | str, check: bool = True, ignore_errors: bool = False) -> Tuple[str, str, int]:
    """Runs a command synchronously and returns (stdout, stderr, return_code)."""
    ...
  def spawn(self, command: Sequence[str] | str, **kwargs) -> subprocess.Popen:
    """Spawns an asynchronous background process (like ffmpeg or whisper-stream)."""
    ...
# class ShellProtocol

class SystemShell:
  """Production implementation of ShellProtocol with logger injection."""
  def __init__(self, logger: Optional[LoggerProtocol] = None): self.logger = logger or NullLogger()
  def _normalize_command(self, command: Sequence[str] | str) -> list[str]:
    """Ensures commands are converted safely to a list of arguments."""
    if isinstance(command, str): return shlex.split(command)
    return list(map(str, command))
  def run(self, command: Sequence[str] | str, check: bool = True, ignore_errors: bool = False) -> Tuple[str, str, int]:
    cmd_args = self._normalize_command(command); cmd_str = " ".join(cmd_args)
    self.logger.debug(f"Executing: '{cmd_str}'")
    process = subprocess.Popen(cmd_args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    stdout, stderr = process.communicate(); return_code = process.poll() or 0
    if return_code != 0 and not ignore_errors:
      error_msg = f"Command failed ({return_code}): '{cmd_str}'"
      self.logger.error(f"{error_msg}\nStderr: {stderr.strip()}")
      if check: raise ShellExecutionError(cmd_str, return_code, stdout, stderr)
    return stdout, stderr, return_code
  def spawn(self, command: Sequence[str] | str, **kwargs) -> subprocess.Popen:
    cmd_args = self._normalize_command(command); cmd_str = " ".join(cmd_args)
    self.logger.debug(f"Spawning process: '{cmd_str}'"); return subprocess.Popen(cmd_args, **kwargs)
# class SystemShell


#
# Config

@dataclass(frozen=True)
class AudioConfig:
  outputAudioFileStem: str="appAudioRecordByScript"
  microphoneDeviceNameKeyword: str="SomeDevice"
  speakerDeviceNameKeyword: str="SomeDevice"
  playbackCaptureApplicationNameKeywords=["chrome"]
  recorderApplicationNameKeywords=["ffmpeg", "lavf"]
  sinkName: str="call_mix"
  whisperCppDir: str="path/to/whisper.cpp"
  logFileStem = "audioPipelineLog"
  loggerType=FileLogger
  shellType=SystemShell
  timestampFormat: str="%Y%m%d_%H%M%S"
  default = None
  @classmethod
  def timestamp(cls, timestampFormat: str) -> str: return datetime.now().strftime(timestampFormat)
# class AudioConfig
Conf = AudioConfig

class ScriptLogShell:
  "Encapsulates logging, shell execution, and output file paths."
  def __init__(self, confType=Conf, loggerType: Type[LoggerProtocol]=Conf.loggerType,
   shellType: Type[ShellProtocol]=Conf.shellType, outputAudioFileStem: str=Conf.outputAudioFileStem,
   logFileStem: str=Conf.logFileStem, timestampFormat: str=Conf.timestampFormat):
    super().__init__(); self.loggerType = loggerType; self.shellType= shellType;
    self.outputAudioFileStem = outputAudioFileStem; self.logFileStem = logFileStem
    self.timestampFormat = timestampFormat; self.refresh()
  def refresh(self) -> None:
    "Generates a fresh timestamp and updates all log/audio paths and log handlers."
    self.timestamp = datetime.now().strftime(self.timestampFormat); self.logFile = self.logFileName()
    self.logger = self.loggerType(logFile=self.logFile); self.shell = self.shellType(logger=self.logger)
    self.refreshOutputAudioFile(self.timestamp)
  def logFileName(self, timestampStr: str=None) -> str:
    return self.fileFromStem(self.logFileStem, "txt", timestampStr)
  def refreshOutputAudioFile(self, timestampStr: str=None) -> str:
    self.outputAudioFile = self.outputAudioFileName(timestampStr); return self
  def outputAudioFileName(self, timestampStr: str=None) -> str:
    return self.fileFromStem(self.outputAudioFileStem, "wav", timestampStr)
  def fileFromStem(self, fileStem: str, fileExt: str, timestampStr: str=None) -> str:
    timestampStr = timestampStr or Conf.timestamp(self.timestampFormat)
    return f"{fileStem}_{timestampStr}.{fileExt}"
# class ScriptLogShell

class LogShellUser:
  "Short-hand helper methods to use inside class implementation"
  def __init__(self, logShell: ScriptLogShell=ScriptLogShell()):
    super().__init__(); self.logShell = logShell
  def logDebug(self, msg: str): return self.logShell.logger.debug(msg)
  def logInfo(self, msg: str): return self.logShell.logger.info(msg)
  def logWarn(self, msg: str): return self.logShell.logger.warning(msg)
  def logError(self, msg: str): return self.logShell.logger.error(msg)
  def shRun(self, command: Sequence[str] | str, check: bool = True,
   ignore_errors: bool = False) -> Tuple[str, str, int]:
    return self.logShell.shell.run(command, check, ignore_errors)
  def shSpawn(self, command: Sequence[str] | str, **kwargs) -> subprocess.Popen:
    return self.logShell.shell.spawn(command, **kwargs)
# class LogShellUser


#
# Scripts
class AppRecordBase:
  def __init__(self): super().__init__()
  def verifyAudioHealth(self):
    self.recorder.enforceActive(self.captureInputSourceName())
    self.mixer.enforceCallMixNullSinkByKeyword(self.micKeyword, self.speakerKeyword)
    self.mixer.routeAppPlaybackToCallMix(self.playbackAppKeywords)
  # helpers
  def startupTracePrintLog(self, apps: list[str], recorders: list[str]) -> "Self":
    print(f"\n=======================================================")
    print(f"  App recorder running {apps} recorded by {recorders}")
    print(f"  Output to {self.recorder.logShell.outputAudioFile}")
    print(f"=======================================================\n")
    return self
  def waitForPulseaudioConfigToSetup(self):
    time.sleep(2); return self
  def waitForRecorderToRegisterInPulseaudio(self) -> "Self":
    time.sleep(2); return self
  def captureInputSourceName(self): return self.mixer.sinkName + ".monitor"
# class AppRecordBase

class AppAudioRecordTranscribe(AppRecordBase):
  def __init__(self, outputAudioFileStem=Conf.outputAudioFileStem,
   microphoneDeviceNameKeyword: str=Conf.microphoneDeviceNameKeyword,
   speakerDeviceNameKeyword: str=Conf.speakerDeviceNameKeyword,
   playbackCaptureApplicationNameKeywords: list[str]=Conf.playbackCaptureApplicationNameKeywords,
   recorderApplicationNameKeywords: list[str]=Conf.recorderApplicationNameKeywords,
   whisperCppDir: str=Conf.whisperCppDir):
    super().__init__(); self.scriptLogShellFileRuntime = ScriptLogShell()
    self.mixer = PulseAudioMixer(logShell=self.scriptLogShellFileRuntime)
    self.recorder = AudioCapture(self.scriptLogShellFileRuntime)
    self.transcriber = AudioTranscription(whisperCppDir=whisperCppDir)
    self.micKeyword = microphoneDeviceNameKeyword; self.speakerKeyword = speakerDeviceNameKeyword
    self.playbackAppKeywords = playbackCaptureApplicationNameKeywords
    self.recordAppKeywords = recorderApplicationNameKeywords
  def stereoRecordTranscribeApp(self) -> "Self":
    try:
      self.stereoRecordTranscribeAppStart(); print("Press ctrl+C to keyboard break stop")
      while True: time.sleep(1); self.verifyAudioHealth()
    except KeyboardInterrupt: print(f"Recording stopped by key interrupt")
    finally:
      print(f"Loaded PulseAudio module ids upon stop {self.mixer.loadedModules}")
      self.transcriber.stopLiveStream()
      self.recorder.stopRecording(); self.mixer.unloadPulseaudioModulesCreatedBySession()
    return self
  def stereoRecordTranscribeAppStart(self) -> "Self":
    self.scriptLogShellFileRuntime.refresh()
    self.mixer.createCallMixNullSinkAndLoopbacksByKeyword(self.micKeyword, self.speakerKeyword)
    self.waitForPulseaudioConfigToSetup()
    self.recorder.startStereoRecord(self.captureInputSourceName())
    self.waitForRecorderToRegisterInPulseaudio()
    appList = self.mixer.routeAppPlaybackToCallMix(self.playbackAppKeywords)
    recorderList = self.mixer.routeAppRecordingToCallMixMonitor(self.recordAppKeywords)
    self.transcriber.startLiveStream("interview_live.txt")
    self.startupTracePrintLog(appList, recorderList)
    return self
# class AppAudioRecordTranscribe

class AppAudioRecord(AppRecordBase):
  "Encapsulate script run recording browser audio by PulseAudio config"
  def __init__(self, microphoneDeviceNameKeyword: str=Conf.microphoneDeviceNameKeyword,
   speakerDeviceNameKeyword: str=Conf.speakerDeviceNameKeyword,
   playbackCaptureApplicationNameKeywords: list[str]=Conf.playbackCaptureApplicationNameKeywords,
   recorderApplicationNameKeywords: list[str]=Conf.recorderApplicationNameKeywords):
    super().__init__(); self.scriptLogShellFileRuntime = ScriptLogShell()
    self.mixer = PulseAudioMixer(logShell=self.scriptLogShellFileRuntime)
    self.recorder = AudioCapture(self.scriptLogShellFileRuntime)
    self.micKeyword = microphoneDeviceNameKeyword; self.speakerKeyword = speakerDeviceNameKeyword
    self.playbackAppKeywords = playbackCaptureApplicationNameKeywords
    self.recordAppKeywords = recorderApplicationNameKeywords
  def stereoRecordApp(self) -> "Self":
    try:
      self.stereoRecordAppStart(); print("Press ctrl+C to keyboard break stop")
      while True: time.sleep(1); self.verifyAudioHealth()
    except KeyboardInterrupt: print(f"Recording stopped by key interrupt")
    finally:
      print(f"Loaded PulseAudio module ids upon stop {self.mixer.loadedModules}")
      self.recorder.stopRecording(); self.mixer.unloadPulseaudioModulesCreatedBySession()
    return self
  def stereoRecordAppStart(self) -> "Self":
    self.scriptLogShellFileRuntime.refresh()
    self.mixer.createCallMixNullSinkAndLoopbacksByKeyword(self.micKeyword, self.speakerKeyword)
    self.waitForPulseaudioConfigToSetup()
    self.recorder.startStereoRecord(self.captureInputSourceName())
    self.waitForRecorderToRegisterInPulseaudio()
    appList = self.mixer.routeAppPlaybackToCallMix(self.playbackAppKeywords)
    recorderList = self.mixer.routeAppRecordingToCallMixMonitor(self.recordAppKeywords)
    self.startupTracePrintLog(appList, recorderList)
    return self
# class AppAudioRecord


#
# Script components
class PulseAudioMixer(LogShellUser):
  """Manages PulseAudio virtual sink and loopbacks for call recording."""
  def __init__(self, sinkName: str=Conf.sinkName, logShell: ScriptLogShell=ScriptLogShell()):
    super().__init__(logShell); self.sinkName = sinkName; self.loadedModules = []
  # setup, device routes
  # main setup routines
  def createCallMixNullSinkAndLoopbacksByKeyword(self,
   microphoneDeviceNameKeyword: str=Conf.microphoneDeviceNameKeyword,
   speakerDeviceNameKeyword: str=Conf.speakerDeviceNameKeyword) -> "Self":
    "setup config"
    self.logInfo("[PulseAudio] Setting up virtual sink and loopbacks...")
    self.createNullSink(); self.routeMicLoopbackToCallMixByKeywordSearch(microphoneDeviceNameKeyword)
    self.routeAudioLoopbackToCallMixByKeywordSearch(speakerDeviceNameKeyword)
    self.logInfo("[PulseAudio] Setup complete. Use pavucontrol to see config'd playback/recording devices.")
    return self
  def createCallMixNullSinkAndLoopbacksForManualPavucontrolSetup(self) -> "Self":
    "setup defaults"
    self.logInfo("[PulseAudio] Setting up virtual sink and loopbacks...")
    self.createNullSink(); self.routeMicLoopbackToCallMixDefaults(); self.routeAudioLoopbackToCallMixDefaults()
    self.logInfo("[PulseAudio] Setup complete. Use pavucontrol to manual config playback/recording devices.")
    return self
  def enforceCallMixNullSinkByKeyword(self, microphoneDeviceNameKeyword: str,
   speakerDeviceNameKeyword: str) -> bool:
    if not self.sinkExists():
      self.logWarn("[WARNING] call_mix sink vanished. Re-creating routing...")
      self.createCallMixNullSinkAndLoopbacksByKeyword(microphoneDeviceNameKeyword,
       speakerDeviceNameKeyword)
      return False
    return True
  # setup procedure step helpers
  def createNullSink(self) -> int:
    outputSinkId = self.pactlLoadModule(f'pactl load-module module-null-sink sink_name={self.sinkName} '
                                        f'sink_properties=device.description="{self.sinkName}"')
    self.loadedModules.append(outputSinkId); return outputSinkId
  def routeMicLoopbackToCallMixByKeywordSearch(self, micDeviceKeyword: str) -> int:
    micSource = self.pulseaudioFullSourceNameByKeywordSkipError("source", micDeviceKeyword)
    return self.routeMicLoopbackToCallMixByExactDeviceName(micSource)
  def routeMicLoopbackToCallMixDefaults(self) -> int: return self.routeMicLoopbackToCallMixByExactDeviceName()
  def routeMicLoopbackToCallMixByExactDeviceName(self, micSource: str="") -> int:
    micArg = f" source={micSource}" if micSource else ""
    outputLoopbackId = self.pactlLoadModule(f"pactl load-module module-loopback{micArg} sink={self.sinkName}")
    self.loadedModules.append(outputLoopbackId); return outputLoopbackId
  def routeAudioLoopbackToCallMixByKeywordSearch(self, speakerDeviceKeyword: str) -> int:
    speakerSink = self.pulseaudioFullSourceNameByKeywordSkipError("sink", speakerDeviceKeyword)
    return self.routeAudioLoopbackToCallMixByExactDeviceName(speakerSink)
  def routeAudioLoopbackToCallMixDefaults(self) -> int:
    return self.routeAudioLoopbackToCallMixByExactDeviceName()
  def routeAudioLoopbackToCallMixByExactDeviceName(self, speakerSink: str="") -> int:
    speakerArg = f" sink={speakerSink}" if speakerSink else ""
    outputLoopbackId = self.pactlLoadModule(
     f"pactl load-module module-loopback source={self.sinkName}.monitor{speakerArg}")
    self.loadedModules.append(outputLoopbackId); return outputLoopbackId
  # cleanup
  def unloadPulseaudioModulesCreatedBySession(self) -> "Self":
    "cleanup"
    self.logInfo("[PulseAudio] Unloading PulseAudio modules..."); remove = set()
    for mod_id in reversed(self.loadedModules):
      try: self.shRun(f"pactl unload-module {mod_id}"); remove.add(mod_id)
      except Exception as e: self.logInfo(f"[PulseAudio] Failed unloading module {mod_id}: {e}")
    self.loadedModules = [x for x in self.loadedModules if x not in remove]; return self
  # setup, app routes
  def routeAppPlaybackToCallMix(self, appKeywords: Sequence[str] | str = ["chrome"]) -> list[str]:
    "Finds running application playback stream (e.g., Chrome) and moves playback to sink."
    targetSinkIndex = self.sinkIndexOfName(self.sinkName)
    if missingNullSink := targetSinkIndex is None:
      self.logWarn(f"[PulseAudio] Warning: Sink '{self.sinkName}' does not exist.")
      return []
    def movePlaybackStream(inputStream: dict, appTitle: str) -> None:
      inputStreamId = inputStream["index"]; currentSinkIndex = inputStream.get("sink")
      if unattached := currentSinkIndex != targetSinkIndex and str(currentSinkIndex) != self.sinkName:
        self.logInfo(f"[PulseAudio] Moving playback of {appTitle} (ID {inputStreamId}) -> {self.sinkName}")
        self.shRun(f"pactl move-sink-input {inputStreamId} {self.sinkName}")
    return self.forEachMatchingPulseAudioStream(self.pulseaudioSinkInputDicts(), appKeywords,
      movePlaybackStream)
  def routeAppRecordingToCallMixMonitor(self, appKeywords: Sequence[str] | str = ["ffmpeg"]) -> list[str]:
    "Finds active recording stream (e.g., FFmpeg/whisper-stream) and points recording to sinkName.monitor."
    target = f"{self.sinkName}.monitor"
    def moveRecordingStream(outputStream: dict, appTitle: str) -> None:
      outputStreamId = outputStream["index"]
      self.logInfo(f"[PulseAudio] Moving recording stream {appTitle} (ID {outputStreamId}) -> {target}")
      self.shRun(f"pactl move-source-output {outputStreamId} {target}")
    return self.forEachMatchingPulseAudioStream(self.pulseaudioSourceOutputDicts(), appKeywords,
      moveRecordingStream)
  # pulse audio queries
  def pulseaudioFullSourceNameByKeywordSkipError(self, deviceType: str, searchKeyword: str) -> str:
    try: return self.pulseaudioFullSourceNameByKeyword(deviceType, searchKeyword)
    except Exception as e: self.logError(f"[PulseAudio] Device lookup error: {e}")
    return None
  def pulseaudioFullSourceNameByKeyword(self, deviceType: str, searchKeyword: str) -> str:
    devices = self.pulseaudioDeviceDicts(deviceType)
    for dev in devices:
      name = dev.get("name", "")
      desc = dev.get("description", "")
      if skipMonitors := deviceType == "source" and name.endswith(".monitor"): continue
      if (searchKeyword.lower() in name.lower() or searchKeyword.lower() in desc.lower()): return name
    return None
  def pulseaudioDeviceDicts(self, sinkOrSourceDeviceType: str="sink") -> list[dict]:
    arg = "sinks" if sinkOrSourceDeviceType == "sink" else "sources"
    deviceDetailsJson, _, _ = self.shRun(f"pactl -f json list {arg}"); return json.loads(deviceDetailsJson)
  def pulseaudioSinkInputDicts(self) -> list[dict]: return self.jsonSh(f"pactl -f json list sink-inputs")
  def pulseaudioSourceOutputDicts(self) -> list[dict]: return self.jsonSh(f"pactl -f json list source-outputs")
  def sinkExists(self) -> bool:
    sinksJsonText, _, _ = self.shRun('pactl -f json list sinks'); return self.sinkName in sinksJsonText
  def sinkIndexOfName(self, targetSinkName: str | None = None) -> int | None:
    "Finds integer index of a sink matching sink name (e.g. 'call_mix')."
    targetName = targetSinkName or self.sinkName
    for sink in self.pulseaudioDeviceDicts("sink"):
      if sink.get("name") == targetName: return sink.get("index")
    return None
  def forEachMatchingPulseAudioStream(self, streams: list[dict], appKeywords: Sequence[str] | str,
   onMatchAction: Callable[[int, str], None]) -> list[str]:
    "Over PulseAudio streams, match application keywords and executing onMatchAction callback on hits."
    matchedAppTitles: list[str] = []; normalizedKeywords = self.pluralStr(appKeywords)
    for stream in streams:
      binary, appTitle = self.extractPulseAudioAppMetadata(stream)
      if self.isAnyKeywordMatch(normalizedKeywords, [binary, appTitle]):
        onMatchAction(stream, appTitle); matchedAppTitles.append(appTitle)
    return matchedAppTitles
  def extractPulseAudioAppMetadata(self, streamDict: dict) -> tuple[str, str]:
    "Extracts normalized (lowercase) binary path and application title from stream properties dict."
    props = streamDict.get("properties", {}); binary = props.get("application.process.binary", "").lower()
    appTitle = props.get("application.name", "").lower(); return binary, appTitle
  def pactlLoadModule(self, cmd: str) -> int: return self.parsePactlId(self.shRun(cmd)[0])
  def parsePactlId(self, pactlStdout: str) -> int: return int(pactlStdout.strip()) 
  # helpers
  def jsonSh(self, cmd: str):
    jsonTextStdout, _, _ = self.shRun(cmd)
    return json.loads(jsonTextStdout) if jsonTextStdout else []
  def isAnyKeywordMatch(self, keywords: Sequence[str], texts: Sequence[str]) -> bool:
    return any(keyword.lower() in text.lower() for keyword in keywords for text in texts)
  def pluralStr(self, s: Sequence[str] | str) -> list[str]: return [s] if isinstance(s, str) else list(s)
# class PulseAudioMixer

class AudioCapture(LogShellUser):
  "Handles audio recording via FFmpeg."
  def __init__(self, logShell: ScriptLogShell=ScriptLogShell()):
    super().__init__(logShell); self.process = None
  def startStereoRecord(self, inputSource: str=f"{Conf.sinkName}.monitor"):
    "Records dual-channel stereo (Left=Interviewer, Right=Candidate)."
    outputWav = self.logShell.outputAudioFile
    cmd = ["ffmpeg", "-n", "-thread_queue_size", "2048", "-f", "pulse", "-i", inputSource,
           "-ac", "2", "-ar", "16000", "-flush_packets", "1", outputWav,]
    self.logInfo(f"[AudioCapture] Starting dual-channel recording to {outputWav}...")
    self.process = self.shSpawn(cmd, stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return self
  def stopRecording(self):
    "Stops the FFmpeg process gracefully."
    if self.isAlive():
      self.logInfo("[AudioCapture] Stopping recording...")
      self.process.send_signal(signal.SIGINT)
      try: self.process.wait(timeout=3)
      except subprocess.TimeoutExpired: self.process.kill()
      self.logInfo("[AudioCapture] Recording saved.")
    return self
  def isAlive(self) -> bool: return self.process is not None and self.process.poll() is None
  def enforceActive(self, inputSource: str=f"{Conf.sinkName}.monitor") -> bool:
    if not self.isAlive():
      self.logWarn("[CRITICAL] Recording process died! Attempting restart...")
      self.logShell.refreshOutputAudioFile()
      self.startStereoRecord(inputSource); return False
    return True
# class AudioCapture

class AudioTranscription:
  "Manages whisper-stream live transcription and post-call Python Whisper execution."
  def __init__(self, whisperCppDir: str):
    super().__init__()
    self.whisperCppDir = Path(whisperCppDir).resolve()
    self.stream_bin = self.whisperCppDir / "build" / "bin" / "whisper-stream"
    self.stream_process = None
  def launchTranscription(self, outputTextFile: str):
    return self.launchTranscriptionBasic(outputTextFile)
  def launchTranscriptionBasic(self, outputTextFile: str):
    return self.startLiveStream(outputTextFile, threads=3, audioStepSizeMilliseconds=3000,
     audioLengthMilliseconds=12000, audioToKeepFromPreviousStepMilliseconds=2000)
  def launchTranscriptionOtherWay(self):
    return self.startLiveStream(outputTextFile, threads=2, audioStepSizeMilliseconds=3000,
     audioLengthMilliseconds=10000)
  def launchTranscriptionNearerRealTime(self):
    return self.startLiveStream(outputTextFile, threads=4, audioStepSizeMilliseconds=1000,
     audioLengthMilliseconds=3000, audioToKeepFromPreviousStepMilliseconds=200,)
  def startLiveStream(self, outputTextFile: str="interview_live.txt",
   model_path: str = "models/ggml-base.en.bin", threads: int = 4, audioStepSizeMilliseconds: int = 3000,
   audioLengthMilliseconds: int = 12000, audioToKeepFromPreviousStepMilliseconds: int = 2000,
   voiceActivityDectionThreshold: float = 0.6,):
    "Launches whisper-stream in the background with optimized CPU parameters."
    abs_model = self.whisperCppDir / model_path
    cmd = [str(self.stream_bin), "-m", str(abs_model), "-t", str(threads),
     "--step", str(audioStepSizeMilliseconds),
     "--length", str(audioLengthMilliseconds), "--keep", str(audioToKeepFromPreviousStepMilliseconds),
     "-vth", str(voiceActivityDectionThreshold), "-f", outputTextFile,]
    print(f"[AudioTranscription] Launching whisper-stream logging to {outputTextFile}...")
    self.stream_process = popen(cmd, cwd=str(self.whisperCppDir))
    return self
  def stopLiveStream(self):
    "Stops the live whisper-stream process."
    if self.stream_process and self.stream_process.poll() is None:
      print("[AudioTranscription] Stopping whisper-stream...")
      self.stream_process.terminate()
      self.stream_process.wait()
  @classmethod
  def processStereoPostCall(cls, wav_path: str, model_name: str = "base.en") -> dict:
    "Splits stereo WAV into L/R channels and transcribes both with OpenAI Whisper."
    import whisper
    wav_file = Path(wav_path)
    left_wav = wav_file.parent / f"{wav_file.stem}_left.wav"
    right_wav = wav_file.parent / f"{wav_file.stem}_right.wav"
    print("[Post-Process] Splitting stereo file into Left and Right channels...")
    sh(f"ffmpeg -y -i {wav_path} -map_channel 0.0.0 {left_wav} -map_channel 0.0.1 {right_wav}")
    print(f"[Post-Process] Loading Python Whisper model ({model_name})...")
    model = whisper.load_model(model_name)
    print("[Post-Process] Transcribing Interviewer channel (Left)...")
    interviewer = model.transcribe(str(left_wav))
    print("[Post-Process] Transcribing Candidate channel (Right)...")
    candidate = model.transcribe(str(right_wav))
    return {"interviewer": interviewer, "candidate": candidate}
# class AudioTranscription

def sh(command: str, stringsWithSpaces: list[str] = None) -> Tuple[str, str]:
  "public fn to run the given string as a shell command and return both stdout and stderr."
  from subprocess import Popen, PIPE
  print(f"Run command in shell '{command}'")
  process = Popen(tokenizeByWhitespace(command, stringsWithSpaces), stdout=PIPE, stderr=PIPE)
  stdout, stderr = process.communicate(); returnCode = process.poll()
  if returnCode != 0: raise Exception(f"Command failed in shell? Return code of {returnCode}?"
                                      f"\nstdout:{stdout}\nstderr:{stderr}\n")
  return stdout.decode(encoding="utf-8"), stderr.decode(encoding="utf-8")

def popen(commandList: list[str], *args, **kwargs):
  "public fn to run given string list as space sep'd shell command and return pid"
  cmd = " ".join(map(str, commandList)); print(f"Run command in shell '{cmd}'")
  return subprocess.Popen(commandList, *args, **kwargs)


# Example Pipeline Execution Script
if __name__ == "__main__":
  # Specify your path to whisper.cpp
  WHISPER_DIR = Conf.whisperCppDir
  mixer = PulseAudioMixer()
  recorder = AudioCapture("interview_call_raw.wav")
  transcriber = AudioTranscription(whisperCppDir=WHISPER_DIR)

  try:
    # 1. Initialize PulseAudio routing
    mixer.createCallMixNullSinkAndLoopbacksByKeyword()
    # 2. Start dual-channel raw recording
    recorder.startStereoRecord()
    # 3. Start live stream transcription (with optimized 12s/3s windowing)
    transcriber.startLiveStream("interview_live.txt")
    print("\n--- Live Session Active. Press Ctrl+C to stop interview session. ---\n")
    while True: time.sleep(1)
  except KeyboardInterrupt:
    print("\nSession interrupted by user.")
  finally:
    # Cleanup processes
    transcriber.stopLiveStream()
    recorder.stopRecording()
    mixer.unloadPulseaudioModulesCreatedBySession()
    # Post-process stereo channels for clean RAG ingestion
    if Path("interview_call_raw.wav").exists():
      results = AudioTranscription.processStereoPostCall("interview_call_raw.wav")
      # Combine and print/save transcript
      print("\n=== Post-Call Transcript Output ===")
      with open("interview_processed_final.txt", "w") as f:
        f.write("--- INTERVIEWER ---\n")
        f.write(results["interviewer"]["text"] + "\n\n")
        f.write("--- CANDIDATE ---\n")
        f.write(results["candidate"]["text"] + "\n")
      print("Final processed transcript saved to interview_processed_final.txt")
